name: WolvenKit-Check-Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Restore packages
      run: dotnet restore --packages .nuget --runtime win-x64
    
    - name: Build with MSBuild
      run: msbuild  WolvenKit.sln -p:Configuration=Release -p:Platform=x64 -m -p:Runtimeidentifier=win-x64
