name: WolvenKit-Nightly
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v2
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Restore packages
      run: dotnet restore --packages .nuget --runtime win-x64

    - name: Build exe
      run: msbuild WolvenKit/WolvenKit.csproj -p:Configuration=Release -p:Platform=x64 -m -p:Runtimeidentifier=win-x64 -verbosity:minimal

    - name: Build cli
      run: msbuild WolvenKit.CLI/WolvenKit.CLI.csproj -p:Configuration=Release -p:Platform=x64 -m -p:Runtimeidentifier=win-x64 -verbosity:minimal

    - name: copy cli exe to app output
      run: Copy-Item ".\WolvenKit.CLI\bin\Release\net48\win-x64\WolvenKit.CLI.exe" -Destination ".\WolvenKit\bin\x64\Release\net48\win-x64"
    
    - name: Zip Release
      run: |
        cd $Env:GITHUB_WORKSPACE\\WolvenKit\bin
        Compress-Archive -Path ./x64/Release/net48/win-x64/ -DestinationPath WolvenKit.zip
    
    - name: Deploy Nightly
      uses: WebFreak001/deploy-nightly@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
      with:
        upload_url: https://uploads.github.com/repos/WolvenKit/WolvenKit-7/releases/68038231/assets{?name,label} # find out this value by opening https://api.github.com/repos/<owner>/<repo>/releases in your browser and copy the full "upload_url" value including the {?name,label} part
        release_id: 68038231
        asset_path: WolvenKit/bin/WolvenKit.zip
        asset_name: WolvenKit-Nightly-NGE-$$.zip # name to upload the release as, use $$ to insert date (YYYYMMDD) and 6 letter commit hash
        asset_content_type: application/zip # required by GitHub API
        max_releases: 5 # optional, if there are more releases than this matching the asset_name, the oldest ones are going to be deleted
